from ...interface import GatewayConfig, GatewayResponse, PaymentData


def get_client_token(**_):
    """Not implemented for stripe gateway currently. The client token can be
    generated by Stripe's checkout.js or stripe.js automatically.
    """
    return


def authorize(
    payment_information: PaymentData, config: GatewayConfig
) -> GatewayResponse:
    pass


def capture(payment_information: PaymentData, config: GatewayConfig) -> GatewayResponse:
    pass


def refund(payment_information: PaymentData, config: GatewayConfig) -> GatewayResponse:
    pass


def void(payment_information: PaymentData, config: GatewayConfig) -> GatewayResponse:
    pass


def process_payment(
    payment_information: PaymentData, config: GatewayConfig
) -> GatewayResponse:
    pass
